/**
 * GST return module records.
 *
 * Kept in their own namespace, and their own Firestore collections, because
 * returns are a separate concern from billing. Nothing here appears on an
 * invoice screen, and the whole module is hidden from businesses it does not
 * apply to.
 */

import type { CivilDate, MonthPeriod } from '@/lib/dates';

export type Iso8601 = string;

/** Which official form a period's work belongs to. */
export type ReturnForm = 'GSTR-1' | 'GSTR-3B' | 'GSTR-1A' | 'IFF';

/**
 * The lifecycle of a period, mapped to what is actually TRUE at each point.
 *
 * The distinction that matters most: `uploaded` and `filed` are different
 * states, and only an authoritative acknowledgement moves a period to `filed`.
 * A generated JSON, an upload receipt, a challan or a payment confirmation is
 * never, on its own, proof that a return was filed.
 */
export type ReturnStatus =
  | 'draft'
  | 'needs-review'
  | 'ready'
  | 'uploaded'
  | 'filed'
  | 'reported-filed-unverified'
  | 'failed'
  | 'status-unknown';

export const RETURN_STATUS_LABELS: Record<ReturnStatus, string> = {
  draft: 'Being prepared',
  'needs-review': 'Needs checking',
  ready: 'Ready',
  uploaded: 'Uploaded — being processed',
  filed: 'Filed',
  'reported-filed-unverified': 'Reported filed — verification pending',
  failed: 'Failed',
  'status-unknown': 'Status unknown',
};

// ---------------------------------------------------------------------------
// Source data
// ---------------------------------------------------------------------------

/** Whether input tax credit on a purchase may actually be taken. */
export type ItcEligibility = 'not-reviewed' | 'eligible' | 'ineligible' | 'blocked' | 'partial' | 'deferred';

export interface SupplierBillRecord {
  id: string;
  /** The supplier's GSTIN, where the purchase is from a registered supplier. */
  supplierGstin: string | null;
  supplierName: string;
  /** The supplier's OWN document number, preserved exactly as printed. */
  documentNumber: string;
  /** A normalised form used only for matching. Never shown as the document number. */
  matchKey: string;
  documentDate: CivilDate;
  documentType: 'invoice' | 'debit-note' | 'credit-note';
  /** The period this purchase is being accounted in. */
  period: MonthPeriod;

  taxableValuePaise: number;
  cgstPaise: number;
  sgstPaise: number;
  igstPaise: number;
  cessPaise: number;

  /**
   * Reviewed eligibility. Defaults to `not-reviewed`: appearing in GSTR-2B does
   * NOT by itself make credit claimable, so nothing is claimed automatically.
   */
  itcEligibility: ItcEligibility;
  /** The portion the owner confirmed as claimable, when partial. */
  eligibleCgstPaise: number;
  eligibleSgstPaise: number;
  eligibleIgstPaise: number;
  eligibleCessPaise: number;
  eligibilityNote: string | null;
  eligibilityReviewedByUid: string | null;
  eligibilityReviewedAt: Iso8601 | null;

  /** Reverse charge purchases carry their own liability. */
  reverseCharge: boolean;

  /** Where this record came from. */
  source: 'manual' | 'csv-import' | 'portal-import';
  importBatchId: string | null;
  createdAt: Iso8601;
  updatedAt: Iso8601;
}

/** A sale raised outside this app that still belongs in the return. */
export interface ExternalSaleRecord {
  id: string;
  /** The original document number. NEVER regenerated by this app. */
  documentNumber: string;
  matchKey: string;
  documentDate: CivilDate;
  period: MonthPeriod;
  customerGstin: string | null;
  customerName: string;
  placeOfSupplyStateCode: string | null;
  documentType: 'invoice' | 'credit-note' | 'debit-note';
  taxableValuePaise: number;
  cgstPaise: number;
  sgstPaise: number;
  igstPaise: number;
  cessPaise: number;
  taxRateBp: number;
  source: 'csv-import' | 'portal-import';
  importBatchId: string;
  createdAt: Iso8601;
}

export interface ImportBatchRecord {
  id: string;
  kind: 'supplier-bills' | 'external-sales' | 'gstr-2b';
  filename: string;
  /** SHA-256 of the uploaded bytes, so re-importing the same file is detectable. */
  fileHash: string;
  sizeBytes: number;
  period: MonthPeriod | null;
  rowsSeen: number;
  rowsImported: number;
  rowsSkippedDuplicate: number;
  rowsRejected: number;
  errors: Array<{ row: number; message: string }>;
  importedByUid: string;
  importedAt: Iso8601;
}

/**
 * An imported portal statement (GSTR-2B and friends).
 *
 * Provenance is the point: the period it covers, when the PORTAL generated it,
 * when we imported it, and the hash of what we imported. Stale statements are
 * detectable and block readiness instead of silently underpinning a return.
 */
export interface GstStatementSnapshotRecord {
  id: string;
  gstin: string;
  statementType: 'GSTR-2B' | 'GSTR-1-summary' | 'GSTR-3B-summary' | 'ledger-summary';
  period: MonthPeriod;
  /** When the portal says it generated or recomputed this statement. */
  generatedAt: Iso8601 | null;
  importedAt: Iso8601;
  importedByUid: string;
  fileHash: string;
  importVersion: number;
  /** Parsed rows, normalised. */
  rows: Array<{
    supplierGstin: string | null;
    supplierName: string;
    documentNumber: string;
    matchKey: string;
    documentDate: CivilDate;
    documentType: 'invoice' | 'debit-note' | 'credit-note';
    taxableValuePaise: number;
    cgstPaise: number;
    sgstPaise: number;
    igstPaise: number;
    cessPaise: number;
    /** What the statement itself says about availability. Not our judgement. */
    statementItcAvailable: boolean | null;
  }>;
  /** Marked stale when source data changed after this snapshot was taken. */
  supersededBySnapshotId: string | null;
}

// ---------------------------------------------------------------------------
// Reconciliation
// ---------------------------------------------------------------------------

export type FindingKind =
  | 'matched'
  | 'amount-mismatch'
  | 'date-mismatch'
  | 'missing-in-books'
  | 'missing-in-statement'
  | 'duplicate-in-books'
  | 'duplicate-in-statement'
  | 'fuzzy-match-needs-review';

export type FindingSeverity = 'blocking' | 'warning' | 'info';

export interface ReconciliationFindingRecord {
  id: string;
  period: MonthPeriod;
  gstin: string;
  kind: FindingKind;
  severity: FindingSeverity;
  /** Plain-language summary for the owner. */
  message: string;
  /** What the owner can do about it. */
  whatYouCanDo: string;
  supplierName: string | null;
  supplierGstin: string | null;
  documentNumber: string | null;
  bookAmountPaise: number | null;
  statementAmountPaise: number | null;
  differencePaise: number | null;
  supplierBillId: string | null;
  snapshotId: string | null;
  /** Owner's recorded decision, when they resolved it. */
  reviewedByUid: string | null;
  reviewedAt: Iso8601 | null;
  reviewReason: string | null;
  resolved: boolean;
  createdAt: Iso8601;
}

// ---------------------------------------------------------------------------
// Return periods and versions
// ---------------------------------------------------------------------------

export interface CompletenessDeclaration {
  allSalesIncluded: boolean;
  allPurchasesIncluded: boolean;
  otherLiabilitiesConsidered: boolean;
  /** Explicitly asked, because "no bills" does not mean "nil return". */
  confirmedNilIfEmpty: boolean;
  declaredByUid: string;
  declaredAt: Iso8601;
}

export interface ReturnPeriodRecord {
  /** `${gstin}__${form}__${period}` */
  id: string;
  gstin: string;
  form: ReturnForm;
  period: MonthPeriod;
  /** For QRMP, the quarter a monthly period rolls into. */
  quarterPeriod: MonthPeriod | null;
  status: ReturnStatus;
  /** Verified statutory due date, or null when we do not have a verified rule. */
  dueDate: CivilDate | null;
  dueDateSource: string | null;
  completeness: CompletenessDeclaration | null;
  /** The version the owner approved, if any. */
  approvedVersionId: string | null;
  currentVersionId: string | null;
  blockingReasons: string[];
  lastPreparedAt: Iso8601 | null;
  updatedAt: Iso8601;
}

/**
 * An immutable snapshot of a prepared return.
 *
 * Reopening any source data after review invalidates the approval: the
 * `sourceFingerprint` is recomputed and compared, so an approval can never be
 * carried over onto a payload the owner did not see.
 */
export interface ReturnVersionRecord {
  id: string;
  returnPeriodId: string;
  gstin: string;
  form: ReturnForm;
  period: MonthPeriod;
  versionNumber: number;
  createdAt: Iso8601;
  createdByUid: string;

  /** Hash over every source record that fed this version. */
  sourceFingerprint: string;
  /** Hash of the approved payload, bound to an approval. */
  payloadHash: string;
  rulePackVersion: string;
  schemaVersion: string | null;

  /** The computed tables. Shape depends on the form. */
  workings: Record<string, unknown>;

  approvedByUid: string | null;
  approvedAt: Iso8601 | null;
  /** Set when a later change made this approval invalid. */
  invalidatedAt: Iso8601 | null;
  invalidationReason: string | null;
}

// ---------------------------------------------------------------------------
// Filing
// ---------------------------------------------------------------------------

export interface ProviderConsentRecord {
  id: string;
  gstin: string;
  providerName: string;
  /** Sandbox consent never authorises a production submission. */
  environment: 'sandbox' | 'production';
  grantedByUid: string;
  grantedAt: Iso8601;
  expiresAt: Iso8601 | null;
  revokedAt: Iso8601 | null;
  scope: string[];
}

export type FilingAttemptStatus =
  | 'preparing'
  | 'submitted'
  | 'processing'
  | 'succeeded'
  | 'rejected'
  | 'timed-out'
  | 'unknown';

export interface FilingAttemptRecord {
  id: string;
  returnVersionId: string;
  gstin: string;
  form: ReturnForm;
  period: MonthPeriod;
  environment: 'sandbox' | 'production';
  /** The payload hash approved for THIS attempt. */
  approvedPayloadHash: string;
  /** Provider-supplied idempotency key, reused on retry. */
  idempotencyKey: string;
  status: FilingAttemptStatus;
  providerReference: string | null;
  requestAt: Iso8601;
  responseAt: Iso8601 | null;
  /** Provider errors, kept verbatim for support. */
  errors: Array<{ code: string; message: string; field?: string }>;
  attemptedByUid: string;
}

export interface FilingAcknowledgementRecord {
  id: string;
  filingAttemptId: string;
  gstin: string;
  form: ReturnForm;
  period: MonthPeriod;
  /** The portal's acknowledgement reference. */
  arn: string | null;
  filedAt: Iso8601 | null;
  /** How we learned this: from the provider, or attached by the owner. */
  evidenceSource: 'provider' | 'owner-attached';
  /** Owner-attached evidence is never treated as verified. */
  verified: boolean;
  verificationNote: string | null;
  attachmentName: string | null;
  attachmentHash: string | null;
  recordedByUid: string;
  recordedAt: Iso8601;
}

export type { CivilDate, MonthPeriod };
